/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BookTable: typeof import('./src/components/BookTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Highlights: typeof import('./src/components/Highlights.vue')['default']
    Likes: typeof import('./src/components/Likes.vue')['default']
    Media: typeof import('./src/components/Media.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Replies: typeof import('./src/components/Replies.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SizeMenu: typeof import('./src/components/SizeMenu.vue')['default']
    SizeMenuTreeView: typeof import('./src/components/SizeMenuTreeView.vue')['default']
    Tweet: typeof import('./src/components/Tweet.vue')['default']
  }
}
